# Generated by packages/auth-policy/scripts/codegen.mjs — do not edit by hand.
from typing import Literal

Actor = Literal["public", "authed", "approved", "admin"]

POLICIES: dict[str, tuple[Actor, ...]] = {
    "home.view": ("public",),
    "tools.overview.view": ("public",),
    "tools.snowboard.demo": ("public",),
    "business-plan.view": ("approved",),
    "project-update.view": ("approved",),
    "admin.dashboard": ("admin",),
    "labs.snowboard-jepa.view": ("approved",),
}


def can(actor: Actor, policy_id: str) -> bool:
    allowed = POLICIES.get(policy_id)
    if allowed is None:
        return False
    return actor in allowed
