import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "../../..");
const policiesPath = join(root, "packages/auth-policy/src/policies.ts");
const outPath = join(root, "apps/api/forest_api/_policies.py");

const src = readFileSync(policiesPath, "utf8");
const match = src.match(/export const policies = (\{[\s\S]*?\})\s*as const/);
if (!match) {
  console.error("Could not find policies object in policies.ts");
  process.exit(1);
}

const pyEntries = [];
const entryRe = /['"]([^'"]+)['"]:\s*\[([^\]]*)\]/g;
for (const m of match[1].matchAll(entryRe)) {
  const key = m[1];
  const rawList = m[2];
  const actors = rawList
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => s.replace(/^['"]|['"]$/g, ""));
  const tupleInner = actors.map((a) => `"${a}"`).join(", ");
  pyEntries.push(`    "${key}": (${tupleInner},),`);
}

const py = `# Generated by packages/auth-policy/scripts/codegen.mjs — do not edit by hand.
from typing import Literal

Actor = Literal["public", "authed", "approved", "admin"]

POLICIES: dict[str, tuple[Actor, ...]] = {
${pyEntries.join("\n")}
}


def can(actor: Actor, policy_id: str) -> bool:
    allowed = POLICIES.get(policy_id)
    if allowed is None:
        return False
    return actor in allowed
`;

writeFileSync(outPath, py, "utf8");
console.log("Wrote", outPath);
